export const allSectors = [
    { sector: "Aerospace and Defense" },
    { sector: "Agent Banking" },
    { sector: "Agriculture" },
    { sector: "Art and Culture" },
    { sector: "Automobile" },
    { sector: "Betting Agency" },
    { sector: "Branding, Advertisement, and Marketing" },
    { sector: "Business Management and Development" },
    { sector: "Car Rental" },
    { sector: "Construction" },
    { sector: "Courier Service and Distribution" },
    { sector: "Data Integration" },
    { sector: "E-commerce" },
    { sector: "Education" },
    { sector: "Energy and Utilities" },
    { sector: "Entertainment and Media" },
    { sector: "Environmental Services" },
    { sector: "Financial Institution" },
    { sector: "Gaming and Esports" },
    { sector: "General Contracts and Merchandise" },
    { sector: "Government and Public Administration" },
    { sector: "Healthcare and Pharmaceuticals" },
    { sector: "Hospitality and Tourism"},
    { sector: "IT" },
    { sector: "Identity Verification and Security" },
    { sector: "Insurance" },
    { sector: "Manufacturing and Industrial" },
    { sector: "Media and Communication" },
    { sector: "Mining and Natural Resources" },
    { sector: "NGO (Non-Governmental Organization) and Social Services"},
    { sector: "Professional Services (e.g., legal, consulting)" },
    { sector: "Proptech (Property Technology)" },
    { sector: "Recruitment/HR Management Sector" },
    { sector: "Renewable Energy" },
    { sector: "Research and Development" },
    { sector: "Retail Sector" },
    { sector: "SaaS Development" },
    { sector: "Sports and Fitness" },
    { sector: "Telecommunications" },
    { sector: "Telehealth" },
    { sector: "Transportation" },
    { sector: "Venture Capital" },
    { sector: "Waste Management and Recycling" },
    { sector: 'Other Sector'}
]